# Generated by Django 5.1.4 on 2025-01-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
