# Generated by Django 5.1.4 on 2025-01-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_rename_create_by_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created_at',)},
        ),
    ]
